<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyEngine.Core\MyEngine.Core.csproj" />
    <ProjectReference Include="..\MyEngine.Rendering\MyEngine.Rendering.csproj" />
    <ProjectReference Include="..\MyEngine.ECS\MyEngine.ECS.csproj" />
    <ProjectReference Include="..\MyEngine.Assets\MyEngine.Assets.csproj" />
    <ProjectReference Include="..\MyEngine.Scene\MyEngine.Scene.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Shaders\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.23.0" />
  </ItemGroup>

</Project>
